remove scheduleDuplicateAccountsForDeletion function to hopefully avoid zero user crashes
The are crashes "NullPointerException: _currentUser must not be null" while the diagnosis reports show 0 registered users.
I suppose this is somehow related to the duplicate account deletion which might have bugs.
Tbh i am not able to understand how it can happen but i suggest to remove the duplicate account handling again to see if crash reports for this decrease again.

This commit will revert almost all changes of the PRs:
https://github.com/nextcloud/talk-android/pull/6559
https://github.com/nextcloud/talk-android/pull/6595

Crash that is hopefully be avoided:

Exception in thread "main"
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.talk2/com.nextcloud.talk.conversationlist.ConversationsListActivity}: java.lang.NullPointerException: _currentUser must not be null
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.NullPointerException: _currentUser must not be null
at com.nextcloud.talk.conversationlist.viewmodels.ConversationsListViewModel.<init>(ConversationsListViewModel.kt:87)
at com.nextcloud.talk.conversationlist.viewmodels.ConversationsListViewModel_Factory.newInstance(ConversationsListViewModel_Factory.java:112)

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>