---- Big Squash ----
WIP first draft for Conversation and ChatMessage. (Entity+Dao)

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

WIP add Test for ChatMessagesDao. Failing for now..

java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
	at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
	at androidx.test.core.app.ApplicationProvider.getApplicationContext(ApplicationProvider.java:41)
	at com.nextcloud.talk.data.database.dao.ChatMessagesDaoTest.createDb(ChatMessagesDaoTest.kt:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

Impl Network Monitor

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

Implemented Synchronizer

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

WIP try to get junit test running. Its failing for now with "Test events were not received"

Not all dependencies might make sense in this commit!

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

Implemented ChatMessageEntity and ConversationEntity

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

move test to androidTest

comment out dao attributes for now (just to focus on the test setup)

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

fix test with coroutines

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

reorder build.gradle dependencies

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

add some test assertions

remove conversation_id ("id" for conversation on server)

rename some attributes

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

Implemented ChatMessageJson and ConversationJson and implemented Mapping functions

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

Implemented Converters + Dao

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

Added update functions to Dao

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

Added foundation for OfflineFirstChatRepository

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

ChatMessageModel

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

Tweaked the Synchronizer to fit talk android specifications and updated OfflineFirstChatRepository to reflect the changes

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

Almost finished with OfflineFirstChatRepository, but I need to figure out a way to get the ChatMessage Models while also keeping the Synchronizer repository agnostic

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

Finished OfflineFirstRepository

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

WIP foundation for ConversationInfoRepository and OfflineFirstConversationInfoRepository

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

WIP implemented OfflineFirstConversationInfoRepository + refactored inconvenient code

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>

WIP implemented provider functions for dagger

Signed-off-by: rapterjet2004 <juliuslinus1@gmail.com>