Skip test 'ShareUtils#date'
The test will be skipped on the CI server because it fails there:

    com.nextcloud.talk.utils.ShareUtilsIT > date[android-27(AVD) - 8.1.0] FAILED
       	java.lang.AssertionError: expected:<1207778138000> but was:<1207785338000>
	at org.junit.Assert.fail(Assert.java:88)

Locally the test works fine. For this problem a issue were created.

See: #1737

Signed-off-by: Tim Krüger <t@timkrueger.me>